{% set version = "1.2.2" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-mcgibbsit
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/mcgibbsit_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/mcgibbsit/mcgibbsit_{{ version }}.tar.gz
  sha256: bc6ad411ffcda7838f8f5a8dd054a5a173c3a669fee9e3d2175cf57fca136ffa

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-coda
  run:
    - r-base
    - r-coda

test:
  commands:
    - $R -e "library('mcgibbsit')"           # [not win]
    - "\"%R%\" -e \"library('mcgibbsit')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=mcgibbsit
  license: GPL-2.0-or-later
  summary: '''mcgibbsit'' provides an implementation of Warnes & Raftery''s MCGibbsit run-length diagnostic for a set of (not-necessarily independent) MCMC samplers.  It combines the estimate error-bounding approach of the Raftery and Lewis MCMC run length diagnostic with the between verses within chain approach of the Gelman
    and Rubin MCMC convergence diagnostic.'
  license_family: GPL3
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - conda-forge/r
    - izahn
